name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code with Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pylint

      - name: Run Pylint
        run: |
          pylint src/

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt pytest chispa

      - name: Run Unit Tests with Pytest
        run: |
          pytest tests/

  build-and-deploy:
    name: Build and Deploy Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and Build Package
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install twine
            python setup.py sdist bdist_wheel
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: dist/